In [1]:
# Jessica Gallo
# CSC767 Neural Networks and Deep Learning
# Final
# Part 1
# Execute forward and backward modes of neural network for 3 iterations
# (epochs). This network comprises of a hidden layer with 3 ReLU units and a
# squared-error loss. (Note: Use tanh as activation function in the output unit
# and ReLU for hidden layer)

In [1]:
import numpy as np

# Data
x = np.array(([0.75, 0.80], [0.20, 0.05], [-0.75, 0.80], [0.20, -0.05]))
y = np.array(([1], [1], [-1], [-1]))

inputSize = 2
outputSize = 1
hiddenSize = 3

# weights
w1 = np.array([[0.60, 0.70, 0.00], [0.01, 0.43, 0.88]])
w2 = np.array([[0.02], [0.03], [0.09]])


def sigmoid(s):
    return 1/(1+np.exp(-s))


def relu(s):
    return np.maximum(0, s)


def dRelu(z):
    return np.where(z <= 0)


def tanh(x):
    t = (np.exp(x) - np.exp(-x)) / (np.exp(x) + np.exp(-x))
    return t


def dTanh(x):
    t = (np.exp(x) - np.exp(-x)) / (np.exp(x) + np.exp(-x))
    dt = 1 - t * t
    return dt


# Forward
def forwardProp(x):
    z = np.dot(x, w1)  # dot product
    z2 = relu(z)  # relu activation
    z3 = np.dot(z2, w2)  # dot product
    o = tanh(z3)  # tanh activation function
    return o


def backwardProp(x, y, o, w1, w2, z2):
    o_error = y - o  # error in output
    o_delta = o_error * dTanh(o)  # derivative of tanh to error

    z2_error = o_delta.dot(w2.T)  # z2 error: hidden layer weight made error
    z2_delta = z2_error * dTanh(z2)  # derivative of tanh to z2 error

    w1 += x.T.dot(z2_delta)  # adjusting first set (input to hidden) weights
    w2 += z2.T.dot(o_delta)


z = np.dot(x, w1)
z2 = relu(z)


def train(x, y):
    o = forwardProp(x)
    backwardProp(x, y, o, w1, w2, z2)

# 1st epoch
print('Input: \n' + str(x))
print('Output:\n' + str(y))
print('Predicted Output: \n' + str(forwardProp(x)))
print('Loss: \n' + str(np.mean(np.square(y-forwardProp(x)))))  # mean sum squared loss
print('\n')

# 2nd epoch
train(x, y)
print('Input: \n' + str(x))
print('Output:\n' + str(y))
print('Predicted Output: \n' + str(forwardProp(x)))
print('Loss: \n' + str(np.mean(np.square(y-forwardProp(x)))))  # mean sum squared loss
print('\n')

# 3rd epoch
train(x, y)
print('Input: \n' + str(x))
print('Output:\n' + str(y))
print('Predicted Output: \n' + str(forwardProp(x)))
print('Loss: \n' + str(np.mean(np.square(y-forwardProp(x)))))  # mean sum squared loss
print('\n')


Input: 
[[ 0.75  0.8 ]
 [ 0.2   0.05]
 [-0.75  0.8 ]
 [ 0.2  -0.05]]
Output:
[[ 1]
 [ 1]
 [-1]
 [-1]]
Predicted Output: 
[[0.09827181]
 [0.01121453]
 [0.06327535]
 [0.00594493]]
Loss: 
0.9833225284863827


Input: 
[[ 0.75  0.8 ]
 [ 0.2   0.05]
 [-0.75  0.8 ]
 [ 0.2  -0.05]]
Output:
[[ 1]
 [ 1]
 [-1]
 [-1]]
Predicted Output: 
[[0.7467511 ]
 [0.19426234]
 [0.01071758]
 [0.15869158]]
Loss: 
0.7693660925235322


Input: 
[[ 0.75  0.8 ]
 [ 0.2   0.05]
 [-0.75  0.8 ]
 [ 0.2  -0.05]]
Output:
[[ 1]
 [ 1]
 [-1]
 [-1]]
Predicted Output: 
[[ 0.60236805]
 [ 0.29632006]
 [-0.33662496]
 [ 0.34921737]]
Loss: 
0.7284326415051565


